apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momotaro-traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kchenfs/TableTap2.0.git
    targetRevision: main
    path: k8s/03-traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
