apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momotaro-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kchenfs/TableTap2.0.git
    targetRevision: main
    path: k8s/00-infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
