apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: momotaro-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: momotaro-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /momotaro/dev/API_KEY
    - secretKey: API_DINE_IN
      remoteRef:
        key: /momotaro/dev/API_DINE_IN
